In [1]:
from alphagenome import colab_utils
from alphagenome.data import gene_annotation, genome, track_data, transcript
from alphagenome.models import dna_client
from alphagenome.visualization import plot_components
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

/home1/smaruj/envs/alphagenome/lib/python3.11/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.27.2 is exactly one major version older than the runtime version 6.31.1 at alphagenome/protos/dna_model.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/home1/smaruj/envs/alphagenome/lib/python3.11/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.27.2 is exactly one major version older than the runtime version 6.31.1 at alphagenome/protos/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/home1/smaruj/envs/alphagenome/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
api_key = "AIzaSyBh9ICxEr8WOH63OELhl13TtqI1xvNo6LY"

In [3]:
# default alphagenome model
dna_model = dna_client.create(api_key)

In [4]:
dna_model.output_metadata().concatenate()

,name,strand,Assay title,ontology_curie,biosample_name,biosample_type,biosample_life_stage,data_source,endedness,genetically_modified,nonzero_mean,output_type,gtex_tissue,histone_mark,transcription_factor
0,CL:0000084 ATAC-seq,.,ATAC-seq,CL:0000084,T-cell,primary_cell,adult,encode,paired,False,0.739741,OutputType.ATAC,NaN,NaN,NaN
1,CL:0000100 ATAC-seq,.,ATAC-seq,CL:0000100,motor neuron,in_vitro_differentiated_cells,adult,encode,paired,False,0.273136,OutputType.ATAC,NaN,NaN,NaN
2,CL:0000236 ATAC-seq,.,ATAC-seq,CL:0000236,B cell,primary_cell,adult,encode,paired,False,4.700081,OutputType.ATAC,NaN,NaN,NaN
3,CL:0000623 ATAC-seq,.,ATAC-seq,CL:0000623,natural killer cell,primary_cell,adult,encode,paired,False,0.938715,OutputType.ATAC,NaN,NaN,NaN
4,CL:0000624 ATAC-seq,.,ATAC-seq,CL:0000624,"CD4-positive, alpha-beta T cell",primary_cell,adult,encode,paired,False,4.365206,OutputType.ATAC,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,ENCSR182QNJ,-,PRO-cap,EFO:0001099,Caco-2,cell_line,NaN,encode,NaN,False,14.002803,OutputType.PROCAP,NaN,NaN,NaN
8,ENCSR740IPL,-,PRO-cap,EFO:0002067,K562,cell_line,NaN,encode,NaN,False,15.765458,OutputType.PROCAP,NaN,NaN,NaN
9,ENCSR797DEF,-,PRO-cap,EFO:0002819,Calu3,cell_line,NaN,encode,NaN,False,12.281321,OutputType.PROCAP,NaN,NaN,NaN
10,ENCSR801ECP,-,PRO-cap,CL:0002618,endothelial cell of umbilical vein,primary_cell,NaN,encode,NaN,False,13.973692,OutputType.PROCAP,NaN,NaN,NaN
11,ENCSR860TYZ,-,PRO-cap,EFO:0001200,MCF 10A,cell_line,NaN,encode,NaN,False,8.229502,OutputType.PROCAP,NaN,NaN,NaN

In [5]:
# Load metadata objects for mouse (mm10)
output_metadata = dna_model.output_metadata(
    organism=dna_client.Organism.MUS_MUSCULUS
).concatenate()

In [6]:
output_metadata

,name,strand,Assay title,ontology_curie,biosample_name,biosample_type,biosample_life_stage,data_source,endedness,genetically_modified,nonzero_mean,output_type,gtex_tissue,histone_mark,transcription_factor
0,CL:0000553 ATAC-seq,.,ATAC-seq,CL:0000553,megakaryocyte progenitor cell,primary_cell,adult,encode,single,False,2.005908,OutputType.ATAC,NaN,NaN,NaN
1,CL:0000557 ATAC-seq,.,ATAC-seq,CL:0000557,granulocyte monocyte progenitor cell,primary_cell,adult,encode,single,False,1.801482,OutputType.ATAC,NaN,NaN,NaN
2,CL:0000792 ATAC-seq,.,ATAC-seq,CL:0000792,"CD4-positive, CD25-positive, alpha-beta regula...",primary_cell,adult,encode,paired,False,3.149848,OutputType.ATAC,NaN,NaN,NaN
3,EFO:0005481 ATAC-seq,.,ATAC-seq,EFO:0005481,Patski,cell_line,unknown,encode,paired,False,2.537327,OutputType.ATAC,NaN,NaN,NaN
4,NTR:0004148 ATAC-seq,.,ATAC-seq,NTR:0004148,"activated CD4-positive, CD25-positive, alpha-b...",primary_cell,adult,encode,paired,False,5.302505,OutputType.ATAC,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,4dn:4DNFIC21MG3U,.,in situ Hi-C,EFO:0004038,mouse embryonic stem cell,cell_line,NaN,4dnucleome,NaN,NaN,NaN,OutputType.CONTACT_MAPS,NaN,NaN,NaN
4,4dn:4DNFIHBTUDO9,.,in situ Hi-C,CL:0000207,olfactory receptor cell,primary_cell,NaN,4dnucleome,NaN,NaN,NaN,OutputType.CONTACT_MAPS,NaN,NaN,NaN
5,4dn:4DNFIKK3QG34,.,in situ Hi-C,EFO:0005484,46C,cell_line,NaN,4dnucleome,NaN,NaN,NaN,OutputType.CONTACT_MAPS,NaN,NaN,NaN
6,4dn:4DNFIMV54HXI,.,in situ Hi-C,CL:0000207,olfactory receptor cell,primary_cell,NaN,4dnucleome,NaN,NaN,NaN,OutputType.CONTACT_MAPS,NaN,NaN,NaN
7,4dn:4DNFIS5ZK13C,.,in situ Hi-C,CL:0000945,lymphocyte of B lineage,cell_line,NaN,4dnucleome,NaN,NaN,NaN,OutputType.CONTACT_MAPS,NaN,NaN,NaN

In [7]:
output_metadata["Assay title"].unique()

array(['ATAC-seq', 'LQhCAGE', 'hCAGE', 'DNase-seq', 'total RNA-seq',
       'polyA plus RNA-seq', 'Histone ChIP-seq', 'TF ChIP-seq', nan,
       'in situ Hi-C'], dtype=object)

In [8]:
output_metadata[output_metadata["Assay title"] == "in situ Hi-C"]

,name,strand,Assay title,ontology_curie,biosample_name,biosample_type,biosample_life_stage,data_source,endedness,genetically_modified,nonzero_mean,output_type,gtex_tissue,histone_mark,transcription_factor
0,4dn:4DNFI3M6726I,.,in situ Hi-C,CL:0000207,olfactory receptor cell,primary_cell,NaN,4dnucleome,NaN,NaN,NaN,OutputType.CONTACT_MAPS,NaN,NaN,NaN
1,4dn:4DNFI3QLT3KJ,.,in situ Hi-C,EFO:0001640,B cell derived cell line,primary_cell,NaN,4dnucleome,NaN,NaN,NaN,OutputType.CONTACT_MAPS,NaN,NaN,NaN
2,4dn:4DNFIAVHP5AV,.,in situ Hi-C,EFO:0001640,B cell derived cell line,primary_cell,NaN,4dnucleome,NaN,NaN,NaN,OutputType.CONTACT_MAPS,NaN,NaN,NaN
3,4dn:4DNFIC21MG3U,.,in situ Hi-C,EFO:0004038,mouse embryonic stem cell,cell_line,NaN,4dnucleome,NaN,NaN,NaN,OutputType.CONTACT_MAPS,NaN,NaN,NaN
4,4dn:4DNFIHBTUDO9,.,in situ Hi-C,CL:0000207,olfactory receptor cell,primary_cell,NaN,4dnucleome,NaN,NaN,NaN,OutputType.CONTACT_MAPS,NaN,NaN,NaN
5,4dn:4DNFIKK3QG34,.,in situ Hi-C,EFO:0005484,46C,cell_line,NaN,4dnucleome,NaN,NaN,NaN,OutputType.CONTACT_MAPS,NaN,NaN,NaN
6,4dn:4DNFIMV54HXI,.,in situ Hi-C,CL:0000207,olfactory receptor cell,primary_cell,NaN,4dnucleome,NaN,NaN,NaN,OutputType.CONTACT_MAPS,NaN,NaN,NaN
7,4dn:4DNFIS5ZK13C,.,in situ Hi-C,CL:0000945,lymphocyte of B lineage,cell_line,NaN,4dnucleome,NaN,NaN,NaN,OutputType.CONTACT_MAPS,NaN,NaN,NaN

In [ ]:
BED_FILE = "/project/fudenber_735/tensorflow_models/akita/v2/data/mm10/sequences.bed"

In [ ]:
df = pd.read_csv(BED_FILE, sep="\t", header=None, names=["chrom", "start", "end", "fold"])

In [ ]:
FOLD = 0

In [ ]:
df = df[df["fold"] == f"fold{FOLD}"].reset_index(drop=True)

In [ ]:
# removing cropping
df["ag_start"] = df["start"] + 64*2048
df["ag_end"] = df["end"] - 64*2048

In [ ]:
import random
from pyfaidx import Fasta

In [ ]:
def one_hot_encode_sequence(sequence_obj):
    # Convert pyfaidx.Sequence object to string
    sequence = str(sequence_obj).upper()
    
    # Define the mapping from bases to integers
    base_to_int = {'A': 0, 'C': 1, 'G': 2, 'T': 3}
    valid_bases = list(base_to_int.keys())

    # Step 1: Convert sequence to integer encoding with random base for 'N'
    encoded_indices = []
    for base in sequence:
        if base in base_to_int:
            encoded_indices.append(base_to_int[base])
        else:
            random_base = random.choice(valid_bases)
            encoded_indices.append(base_to_int[random_base])

    # Step 2: One-hot encode the sequence
    encoded_sequence = np.array(encoded_indices)
    one_hot_encoded = np.zeros((4, len(encoded_sequence)), dtype=np.float32)
    one_hot_encoded[encoded_sequence, np.arange(len(encoded_sequence))] = 1

    input_sequence = np.expand_dims(one_hot_encoded, axis=0)

    return input_sequence

In [ ]:
df = df[df["fold"] == f"fold{FOLD}"].reset_index(drop=True)

In [ ]:
fasta_file = "/project/fudenber_735/genomes/mm10/mm10.fa"
genome = Fasta(fasta_file)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
def plot_map(matrix, vmin=-0.6, vmax=0.6, palette="RdBu_r", width=5, height=5):
    fig, axes = plt.subplots(1, 1, figsize=(width, height))

    sns.heatmap(
        matrix,
        vmin=vmin,
        vmax=vmax,
        cbar=False,
        cmap=palette,
        square=True,
        xticklabels=False,
        yticklabels=False,
        ax=axes
    )

    plt.tight_layout()
    plt.show()

In [ ]:
out_dir = "/scratch1/smaruj/alpha_genome_validation/fold0"

In [ ]:
import os

In [ ]:
for i, row in enumerate(df.itertuples(index=False)):
    chrom, start, end = row.chrom, row.ag_start, row.ag_end
    seq = genome[chrom][start:end].seq.upper()
    
    print(i, chrom, start, end)
    
    # print(seq[:10])
    
    output = dna_model.predict_sequence(
        organism=dna_client.Organism.MUS_MUSCULUS,
        sequence=seq,  # Pad to valid sequence length.
        requested_outputs=[dna_client.OutputType.CONTACT_MAPS],
        # ontology_terms=['EFO:0003042'], #H1-hESC
        ontology_terms=['EFO:0004038'] # mouse ontology
    )
    
    # print(output.contact_maps.values.shape)
    
    matrix = output.contact_maps.values[:,:,0]
    
    # plot_map(matrix)
    
    # Construct filename
    filename = f"{chrom}_{start}_{end}.npy"
    filepath = os.path.join(out_dir, filename)

    # Save the map
    np.save(filepath, matrix)
    print(f"Saved: {filepath}")